const config = {
  REACT_APP_GA_MEASUREMENT_ID: process.env.REACT_APP_GA_MEASUREMENT_ID,
  REACT_APP_API_URL: process.env.REACT_APP_API_URL,
  REACT_APP_AI_API_URL: process.env.REACT_APP_AI_API_URL,
  REACT_APP_STRIPE_KEY: process.env.REACT_APP_STRIPE_KEY,
  REACT_APP_APPLICATION_URL: process.env.REACT_APP_APPLICATION_URL,
  REACT_APP_AMPLITUDE_KEY: process.env.REACT_APP_AMPLITUDE_KEY
}

export default config
